version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      MYSQL_DATABASE: delivery
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Aa123456
    ports:
      - '8080:80'
    depends_on:
      - db
  laravel:
    build: ./delivery
    ports:
      - "9000:9000"
    volumes:
      - ./delivery:/var/www/html
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '81:81'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - laravel
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_API_URL=http://localhost:81/api
